# Generated by Django 5.1.6 on 2025-03-24 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('foreground_color', models.CharField(default='#000000', max_length=7, verbose_name='Foreground Color')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Background Color')),
                ('box_size', models.PositiveIntegerField(default=10, verbose_name='Box Size')),
                ('border', models.PositiveIntegerField(default=4, verbose_name='Border Size')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='Share Count')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('default_qr_foreground', models.CharField(default='#000000', max_length=7, verbose_name='Default QR Foreground')),
                ('default_qr_background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Default QR Background')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
